(function () {
  "use strict";

  window.RK_DATA = {
    version: 1,
    account: {
      name: "小许",
      handle: "知乎收藏者",
      scope: "收藏夹 · 收藏内容",
      connected: true,
    },

    themes: [
      {
        id: "learning",
        name: "学习与记忆",
        description: "理解、记忆与长期掌握",
        color: "#4f73e8",
        soft: "rgba(79,115,232,.12)",
        keywords: ["学习", "记忆", "认知", "复盘"],
      },
      {
        id: "ai",
        name: "AI 与效率",
        description: "大模型、工具与工作流",
        color: "#149b8b",
        soft: "rgba(20,155,139,.12)",
        keywords: ["AI", "大模型", "效率", "工具"],
      },
      {
        id: "work",
        name: "职场与表达",
        description: "沟通、写作与职业成长",
        color: "#d28a2e",
        soft: "rgba(210,138,46,.13)",
        keywords: ["职场", "表达", "写作", "沟通"],
      },
      {
        id: "decision",
        name: "决策与思维",
        description: "判断、概率与复杂问题",
        color: "#c45176",
        soft: "rgba(196,81,118,.12)",
        keywords: ["决策", "概率", "逻辑", "判断"],
      },
      {
        id: "mind",
        name: "心理与成长",
        description: "习惯、注意力与自我管理",
        color: "#6c63c8",
        soft: "rgba(108,99,200,.12)",
        keywords: ["习惯", "注意力", "情绪", "成长"],
      },
    ],

    articles: [
      {
        id: "feynman",
        themeId: "learning",
        question: "费曼学习法真的有用吗？",
        title: "费曼学习法：用“讲给外行听”检验自己",
        author: "李思考",
        authorMeta: "计算机研究生",
        votes: 8400,
        savedAt: "3 天前",
        reading: 8,
        initialStatus: "lit",
        mastery: 92,
        tags: ["主动回忆", "理解", "表达"],
        focus: "把“我好像懂了”变成可验证的理解",
        quote: "能不用术语把一件事讲清楚，才算真的理解。",
        relations: ["spaced", "prompt"],
        analysis: {
          surface: {
            conclusion: "费曼学习法的价值不在于“教别人”，而在于用输出暴露理解漏洞。",
            facts: [
              "尝试用自己的语言解释，会强迫大脑检索而不是重复识别。",
              "卡壳的位置通常就是知识结构中缺失的连接。",
              "类比能检验理解，但类比失效时也可能制造新误解。",
            ],
            assumptions: [
              "学习者已经获得了足够准确的基础材料。",
              "讲解对象确实会追问，或者学习者能主动模拟追问。",
            ],
            dependencies: ["可验证的原文", "反馈", "一次真实输出"],
          },
          first: {
            axiom: "理解不是熟悉感，而是能够在新情境中重建因果链。",
            chain: [
              "识别熟悉感不等于掌握。",
              "输出迫使信息从记忆中重新生成。",
              "生成失败的位置暴露了缺失的连接。",
              "针对缺口补课后再次输出，形成闭环。",
            ],
            boundary: "对程序性技能、纯记忆材料，费曼法只能辅助，不能替代实际练习。",
          },
          ideal: {
            essence: "费曼法的本质是“可重建”：离开原文，仍能独立讲清因果。",
            idealForm: "一个外行听完后，能复述核心结论，并问出至少一个有效追问。",
            realityGap: "多数人只是把原文换了几组同义词，并没有真正改变解释层级。",
            counterexample: "把标准答案背给朋友听，朋友点头，但换成新案例就无法判断。",
          },
          transfer: {
            actions: [
              "合上原文，用 150 字写出核心因果链。",
              "找一个真实的人听你讲，并记录对方追问。",
              "把无法回答的问题写成下一轮学习清单。",
            ],
            personalQuestion: "我现在掌握的是结论，还是能独立重建结论的推理过程？",
          },
        },
      },
      {
        id: "spaced",
        themeId: "learning",
        question: "为什么学了就忘，间隔重复真的有用吗？",
        title: "让遗忘曲线替你安排复习",
        author: "陈老师",
        authorMeta: "学习科学答主",
        votes: 5200,
        savedAt: "6 天前",
        reading: 6,
        initialStatus: "planet",
        mastery: 56,
        tags: ["遗忘曲线", "复习", "长期记忆"],
        focus: "把复习安排在“快忘但还没忘”的节点",
        quote: "不是学得不够，而是复习得不够巧。",
        relations: ["feynman", "habits"],
        analysis: {
          surface: {
            conclusion: "间隔重复通过安排适度的回忆难度，让记忆痕迹变得更稳定。",
            facts: [
              "新信息在最初阶段遗忘最快，之后遗忘速度逐渐放缓。",
              "主动回忆比重复阅读更能形成长期记忆。",
              "复习间隔需要随掌握程度逐步拉长。",
            ],
            assumptions: ["材料值得长期保留", "复习内容可以被准确定义"],
            dependencies: ["复习记录", "明确的回忆任务", "稳定的时间安排"],
          },
          first: {
            axiom: "记忆强度来自成功提取，而不是单纯暴露。",
            chain: [
              "阅读带来熟悉感，但熟悉的线索在缺失时无法独立触发回忆。",
              "主动回忆迫使大脑重新建立访问路径。",
              "在遗忘边缘完成提取，会强化这条路径。",
              "随着路径稳定，复习间隔可以延长。",
            ],
            boundary: "没有理解结构、只靠重复背诵时，间隔重复可能只是强化碎片。",
          },
          ideal: {
            essence: "复习不是重新输入，而是在关键时点完成一次高质量提取。",
            idealForm: "在完全不看原文时先回答核心问题，再根据失败点补课。",
            realityGap: "大量复习只是再次阅读，产生“我记住了”的错觉。",
            counterexample: "每天重看笔记十遍，却在一周后无法独立说出核心结论。",
          },
          transfer: {
            actions: [
              "为这组知识写下 3 个必须能独立回答的问题。",
              "先在空白页作答，再打开原文核对。",
              "按 1 天、3 天、7 天记录下一轮复习。",
            ],
            personalQuestion: "如果没有提示，我还能主动重建这条知识链吗？",
          },
        },
      },
      {
        id: "llm",
        themeId: "ai",
        question: "大模型到底是什么？给非技术的人讲讲",
        title: "大模型：一个高速生成合理下一句的系统",
        author: "可达鸭",
        authorMeta: "AI 产品经理",
        votes: 15000,
        savedAt: "1 天前",
        reading: 7,
        initialStatus: "lit",
        mastery: 88,
        tags: ["大模型", "概率", "上下文"],
        focus: "理解生成机制，建立正确使用边界",
        quote: "工具没有立场，怎么使用才有立场。",
        relations: ["prompt", "bayes"],
        analysis: {
          surface: {
            conclusion: "大模型根据上下文预测最可能的后续内容，而不是从数据库中取回标准答案。",
            facts: [
              "模型参数记录的是统计规律，不是可直接检索的事实表。",
              "上下文越明确，生成空间越容易被约束到目标区域。",
              "流畅表达与事实正确并不是同一个能力。",
            ],
            assumptions: ["训练语料中包含目标语言和任务模式", "上下文提供了足够约束"],
            dependencies: ["数据质量", "上下文质量", "验证机制"],
          },
          first: {
            axiom: "生成系统优化的是“下一个输出的概率”，不是“事实是否为真”。",
            chain: [
              "文本被转换为概率分布中的模式。",
              "模型根据上下文为可能的后续词分配概率。",
              "解码策略选择输出路径。",
              "用户看到的答案可以流畅，但仍可能缺少事实依据。",
            ],
            boundary: "需要最新事实、专业责任或高风险判断时，必须引入外部数据与人工复核。",
          },
          ideal: {
            essence: "它是概率生成器，也是可被上下文塑形的任务执行器。",
            idealForm: "把模型当作快速提出候选方案的实习生，而不是最终责任主体。",
            realityGap: "用户常把表达自信误判为知识可靠。",
            counterexample: "模型给出格式完美的法律结论，却引用了不存在的案例。",
          },
          transfer: {
            actions: [
              "对关键结论补一个外部来源。",
              "把问题改写成“基于给定材料完成什么任务”。",
              "要求模型区分事实、推断和不确定性。",
            ],
            personalQuestion: "这个答案的任务是生成内容，还是替我承担最终判断？",
          },
        },
      },
      {
        id: "prompt",
        themeId: "ai",
        question: "怎么提问才能让 AI 真正帮上忙？",
        title: "把 AI 当同事：角色、任务、背景与格式",
        author: "阿康",
        authorMeta: "效率工具博主",
        votes: 7200,
        savedAt: "8 天前",
        reading: 5,
        initialStatus: "planet",
        mastery: 63,
        tags: ["提示词", "工作流", "上下文"],
        focus: "用信息结构降低模型猜测空间",
        quote: "提示词不是咒语，而是一份清晰的任务说明书。",
        relations: ["llm", "feynman"],
        analysis: {
          surface: {
            conclusion: "高质量提示词的核心，是明确角色、任务、背景、约束和输出格式。",
            facts: [
              "含糊目标会让模型在多个任务之间随机选择。",
              "示例能显著降低输出格式的不确定性。",
              "迭代追问比第一次写出完美提示词更可靠。",
            ],
            assumptions: ["模型具备完成任务所需的基础能力", "用户知道成功结果长什么样"],
            dependencies: ["任务定义", "必要背景", "验收标准"],
          },
          first: {
            axiom: "模型只能根据可见上下文优化输出，无法读取你脑中的隐含标准。",
            chain: [
              "任务目标被清晰表达。",
              "关键背景和边界被放入上下文。",
              "输出结构被明确约束。",
              "通过反馈迭代缩小结果空间。",
            ],
            boundary: "当任务本身没有判断标准时，堆叠提示词也无法替代人的决策。",
          },
          ideal: {
            essence: "提示词是把隐性标准外化为可执行约束。",
            idealForm: "一个没有额外背景的协作者，仅看提示词就能理解交付要求。",
            realityGap: "用户往往只说目标，不说背景、边界和验收方式。",
            counterexample: "一句“帮我写好一点”，结果每次输出方向和标准都不同。",
          },
          transfer: {
            actions: [
              "写提示词前，先补一句“成功交付长什么样”。",
              "添加一个正例或反例。",
              "把不满意的地方转换为下一轮约束。",
            ],
            personalQuestion: "如果把这条任务交给真人同事，我还缺哪一项关键信息？",
          },
        },
      },
      {
        id: "report",
        themeId: "work",
        question: "怎么向老板汇报工作，才真正高效？",
        title: "汇报的三层结构：结论、证据、下一步",
        author: "小满",
        authorMeta: "项目管理者",
        votes: 6100,
        savedAt: "2 天前",
        reading: 6,
        initialStatus: "lit",
        mastery: 85,
        tags: ["结论先行", "沟通", "方案"],
        focus: "帮助决策者用最低认知成本完成任务",
        quote: "老板最怕的不是坏消息，而是不知道下一步怎么办。",
        relations: ["interview", "opportunity"],
        analysis: {
          surface: {
            conclusion: "高效汇报先给结论，再给关键证据，最后明确下一步和所需决策。",
            facts: [
              "决策者通常先判断是否需要行动，再决定是否深入细节。",
              "问题与方案同时出现，能显著减少来回沟通。",
              "多条并列信息会增加记忆和比较成本。",
            ],
            assumptions: ["对方的目标与约束足够清楚", "汇报者掌握了关键事实"],
            dependencies: ["可信证据", "明确选项", "下一步责任"],
          },
          first: {
            axiom: "汇报的目的不是展示过程，而是支持决策。",
            chain: [
              "先说明发生什么以及影响是什么。",
              "再用最少证据支撑判断。",
              "列出可选项和权衡。",
              "明确需要对方做什么决定。",
            ],
            boundary: "事故调查、深度复盘等场景仍需完整时间线，不能只报结论。",
          },
          ideal: {
            essence: "把复杂工作压缩成一条可行动的决策路径。",
            idealForm: "对方在一分钟内知道结论、风险和下一步。",
            realityGap: "汇报者按自己的工作时间线讲述，忽略了对方的决策顺序。",
            counterexample: "讲了十分钟背景，最后才说真正需要老板批准的事项。",
          },
          transfer: {
            actions: [
              "第一句写成结论和影响。",
              "只保留支撑决策最必要的三条证据。",
              "给出两个选项并说明推荐方案。",
            ],
            personalQuestion: "对方听完之后，应该知道什么，并具体做什么？",
          },
        },
      },
      {
        id: "interview",
        themeId: "work",
        question: "面试时怎样讲项目才不容易翻车？",
        title: "把面试当成一场清晰的讲题课",
        author: "上岸的鱼",
        authorMeta: "应届求职者",
        votes: 6800,
        savedAt: "4 天前",
        reading: 7,
        initialStatus: "planet",
        mastery: 61,
        tags: ["STAR", "项目表达", "面试"],
        focus: "用结构化叙事证明解决问题的能力",
        quote: "简历是预告片，面试才是正片。",
        relations: ["report"],
        analysis: {
          surface: {
            conclusion: "面试表达的关键是让对方看见你的判断、行动和结果，而不是复述职责。",
            facts: [
              "STAR 结构能把经验压缩成可验证的因果链。",
              "具体数字和取舍过程比形容词更有说服力。",
              "追问通常意味着对方正在测试你的真实参与度。",
            ],
            assumptions: ["项目经历真实且可追溯", "候选人能解释关键决策"],
            dependencies: ["明确问题", "个人行动", "可核验结果"],
          },
          first: {
            axiom: "面试官评估的是未来表现，只能通过过去行为寻找证据。",
            chain: [
              "先定义当时的问题和约束。",
              "说明你拥有的责任和选项。",
              "解释你为何做出关键选择。",
              "用结果和复盘验证判断质量。",
            ],
            boundary: "团队成果不能全部归因于个人，必须清楚区分贡献和依赖。",
          },
          ideal: {
            essence: "把一次经历转化为可重复验证的能力证据。",
            idealForm: "面试官能清楚说出你解决过哪类问题，以及你如何做出判断。",
            realityGap: "候选人从项目背景讲起，却长期不说个人决策。",
            counterexample: "反复说“我参与了”，但追问具体贡献时只能回答团队协作。",
          },
          transfer: {
            actions: [
              "为项目画出“问题—约束—行动—结果”四格。",
              "每个结论配一个可核验数字。",
              "提前准备失败路径和当时的取舍。",
            ],
            personalQuestion: "这件事里，哪些结果没有我就不会发生？",
          },
        },
      },
      {
        id: "opportunity",
        themeId: "decision",
        question: "怎样判断一件事到底值不值得做？",
        title: "机会成本：你真正支付的是被放弃的选项",
        author: "林策",
        authorMeta: "商业策略研究者",
        votes: 4700,
        savedAt: "9 天前",
        reading: 8,
        initialStatus: "planet",
        mastery: 48,
        tags: ["机会成本", "资源配置", "决策"],
        focus: "把隐性损失显性化",
        quote: "成本不是花掉多少，而是因此错过了什么。",
        relations: ["report", "bayes"],
        analysis: {
          surface: {
            conclusion: "判断一件事的价值，不仅看收益，还要看同一资源用于其他选择时的最大价值。",
            facts: [
              "时间、注意力和资金通常不能同时投入多个互斥选项。",
              "沉没成本已经无法回收，不应影响下一阶段选择。",
              "最容易被忽略的是没有发生的损失。",
            ],
            assumptions: ["存在可比较的替代方案", "资源确实稀缺"],
            dependencies: ["替代选项清单", "可比较的收益尺度", "决策周期"],
          },
          first: {
            axiom: "任何选择都发生在一个资源有限的世界里。",
            chain: [
              "选择一个方案就会占用时间和注意力。",
              "被占用的资源无法同时创造其他结果。",
              "因此真实成本等于最佳替代方案的价值。",
              "决策应比较未来增量，而不是追讨过去投入。",
            ],
            boundary: "当探索本身带来无法预知的高价值信息时，短期机会成本不是唯一标准。",
          },
          ideal: {
            essence: "决策的本质是资源在多个未来可能性之间的配置。",
            idealForm: "每个选择都能列出被放弃的最佳选项，并解释为何仍值得。",
            realityGap: "人们只计算显性支出，却忽略锁定的时间与注意力。",
            counterexample: "因为已经投入两年而继续维持低价值项目。",
          },
          transfer: {
            actions: [
              "写出这项选择占用的三项稀缺资源。",
              "列出同一资源最好的替代用途。",
              "把已经无法回收的投入从比较中删除。",
            ],
            personalQuestion: "如果今天以零成本重新选择，我还会继续吗？",
          },
        },
      },
      {
        id: "bayes",
        themeId: "decision",
        question: "如何避免被单条信息带偏判断？",
        title: "贝叶斯更新：让新证据改变信念，而不是控制信念",
        author: "明朗",
        authorMeta: "数据分析师",
        votes: 3900,
        savedAt: "12 天前",
        reading: 9,
        initialStatus: "seed",
        mastery: 18,
        tags: ["概率", "证据", "判断"],
        focus: "用先验与证据强度持续校准判断",
        quote: "理性不是没有立场，而是允许证据改变立场。",
        relations: ["llm", "opportunity"],
        analysis: {
          surface: {
            conclusion: "贝叶斯更新要求同时考虑原有概率与新证据出现的可能性，而不是只盯住最后看到的信息。",
            facts: [
              "基础概率经常比生动个案更能决定真实概率。",
              "证据强度取决于它在不同假设下出现的差异。",
              "判断应根据新信息逐步更新，而不是一次定终身。",
            ],
            assumptions: ["可以给初始判断一个大致概率", "新证据相对可靠"],
            dependencies: ["先验判断", "证据似然", "持续记录"],
          },
          first: {
            axiom: "不确定性是信息不足时对世界的合理表达。",
            chain: [
              "先写下当前判断的概率。",
              "估计证据在正确和错误假设下分别出现的可能性。",
              "根据差异调整判断。",
              "用下一次证据继续更新。",
            ],
            boundary: "当证据来源高度相关或存在系统性偏差时，简单叠加证据会高估确定性。",
          },
          ideal: {
            essence: "判断是可更新的概率，不是需要保护的身份。",
            idealForm: "每条关键证据都能回答：如果结论不成立，我还会看到它吗？",
            realityGap: "人们通常只收集支持既有立场的信息。",
            counterexample: "看到一条成功案例，就把原本 10% 的可能性直接调成 90%。",
          },
          transfer: {
            actions: [
              "写下当前判断及一个粗略概率。",
              "问证据是否只支持单一结论。",
              "记录下一项能真正区分假设的信息。",
            ],
            personalQuestion: "如果结论是错的，我会期待看到什么不同的证据？",
          },
        },
      },
      {
        id: "habits",
        themeId: "mind",
        question: "为什么靠意志力改变习惯总是失败？",
        title: "习惯不是自控问题，而是环境与反馈问题",
        author: "周然",
        authorMeta: "行为设计顾问",
        votes: 7600,
        savedAt: "5 天前",
        reading: 7,
        initialStatus: "planet",
        mastery: 59,
        tags: ["习惯", "环境", "反馈"],
        focus: "把重复行为设计成低阻力系统",
        quote: "稳定行为的秘密，不是更用力，而是更少对抗。",
        relations: ["spaced", "attention"],
        analysis: {
          surface: {
            conclusion: "长期行为改变依赖环境线索、行动阻力和即时反馈的共同设计。",
            facts: [
              "固定环境线索能降低启动时的决策成本。",
              "行动越小，越容易跨过启动门槛。",
              "及时反馈能让大脑把行为与结果连接起来。",
            ],
            assumptions: ["目标行为可以拆成具体动作", "环境可以被局部调整"],
            dependencies: ["稳定线索", "低摩擦入口", "可感知反馈"],
          },
          first: {
            axiom: "人会优先选择当下成本更低的行动。",
            chain: [
              "环境中的线索触发行为候选。",
              "大脑比较行动阻力与预期收益。",
              "低阻力行为更容易被执行。",
              "重复与反馈把行为固化为默认路径。",
            ],
            boundary: "成瘾、严重情绪障碍等复杂问题不能只依赖习惯设计。",
          },
          ideal: {
            essence: "习惯是环境、行动和反馈组成的自动系统。",
            idealForm: "不需要临时动员意志力，线索出现后动作自然发生。",
            realityGap: "用户只设定宏大目标，却没有改变触发环境和最小动作。",
            counterexample: "把跑鞋锁在柜子里，却计划每天靠决心晨跑。",
          },
          transfer: {
            actions: [
              "把目标缩小为一个两分钟内完成的动作。",
              "把它绑定到一个每天必然发生的生活线索。",
              "完成后立即记录并给出可见反馈。",
            ],
            personalQuestion: "我是在改变行为，还是只在重复对自己下达命令？",
          },
        },
      },
      {
        id: "attention",
        themeId: "mind",
        question: "注意力总被打断，还有办法深度工作吗？",
        title: "深度工作：先保护注意力，再谈效率",
        author: "迟野",
        authorMeta: "独立研究者",
        votes: 4300,
        savedAt: "2 周前",
        reading: 8,
        initialStatus: "seed",
        mastery: 24,
        tags: ["注意力", "深度工作", "环境"],
        focus: "降低任务切换，保护认知资源",
        quote: "注意力不是无限的燃料，而是需要被保护的稀缺资源。",
        relations: ["habits"],
        analysis: {
          surface: {
            conclusion: "高质量工作取决于能否形成一段不受切换干扰、目标单一的认知时间。",
            facts: [
              "任务切换会留下注意残留，降低下一项任务表现。",
              "清晰的结束条件能减少中途的未完成焦虑。",
              "中断越容易接触，恢复深度状态的成本越高。",
            ],
            assumptions: ["任务可以在较长时间内连续推进", "中断源可以被部分控制"],
            dependencies: ["明确任务", "屏蔽中断", "恢复仪式"],
          },
          first: {
            axiom: "大脑不能在多个高负荷任务之间无成本切换。",
            chain: [
              "明确当天唯一核心任务。",
              "提前隔离最频繁的中断源。",
              "用固定时长保护连续认知资源。",
              "在阶段结束时记录停点并主动恢复。",
            ],
            boundary: "需要即时响应的岗位无法完全屏蔽中断，只能设计批处理与恢复机制。",
          },
          ideal: {
            essence: "深度工作是注意力的连续性与任务目标的一致性。",
            idealForm: "在固定时间块里，只推进一个明确产物。",
            realityGap: "用户把在线时间误当作深度工作时间。",
            counterexample: "一边写方案一边扫消息，八小时后仍没有完成核心段落。",
          },
          transfer: {
            actions: [
              "为下一次深度工作写一个单一可见产物。",
              "关闭所有非必要通知。",
              "结束前写下具体停点，降低下次启动成本。",
            ],
            personalQuestion: "这段时间结束后，我可以说出哪一个具体产物已经完成？",
          },
        },
      },
    ],

    searchSeeds: [
      {
        id: "search-agents",
        kind: "question",
        title: "AI Agent 真正落地时，最难的是什么？",
        excerpt: "难点通常不在模型能力，而在任务边界、工具可靠性和错误恢复。",
        author: "工业智能观察",
        votes: 2860,
        themeId: "ai",
        tags: ["Agent", "工作流", "可靠性"],
      },
      {
        id: "search-writing",
        kind: "answer",
        title: "怎样把零散笔记写成一篇有观点的文章？",
        excerpt: "先建立中心命题，再让每条材料回答它在论证中承担什么职责。",
        author: "山月",
        votes: 5180,
        themeId: "work",
        tags: ["写作", "观点", "结构"],
      },
      {
        id: "search-systems",
        kind: "question",
        title: "如何建立自己的知识体系，而不是收藏一堆文章？",
        excerpt: "体系不是分类更整齐，而是概念之间能够解释、支撑和反驳彼此。",
        author: "纸上造物",
        votes: 7640,
        themeId: "learning",
        tags: ["知识体系", "连接", "输出"],
      },
      {
        id: "search-risk",
        kind: "answer",
        title: "面对高不确定性的选择，怎样降低决策后悔？",
        excerpt: "把决定拆成可逆与不可逆两类，再为不可逆部分寻找更便宜的信息。",
        author: "决策笔记",
        votes: 3410,
        themeId: "decision",
        tags: ["不确定性", "可逆决策", "风险"],
      },
    ],

    preferences: {
      interests: ["学习与记忆", "AI 与效率", "决策与思维"],
      goal: "建立自己的知识体系",
      depth: "deep",
      angle: "first-principles",
      universeOrder: "cluster",
    },
  };
})();
